# Generated by Django 3.1.7 on 2021-12-03 06:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grade.user')),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Ongoing'), ('2', 'On Probition'), ('3', 'NA')], default='3', max_length=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grade.user')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_taken', models.CharField(max_length=225)),
                ('semester', models.CharField(choices=[('1st', '1st Sem'), ('2nd', '2nd Sem')], default='1st', max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('remarks', models.CharField(choices=[('1', 'Passed'), ('2', 'Failed'), ('3', 'No Grade'), ('4', 'Incomplete')], default='3', max_length=10)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=250, populate_from=['subject_name'])),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.teacher')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.student')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.schoolsubject')),
            ],
            options={
                'ordering': ['-year_taken', '-semester'],
            },
        ),
    ]
